---
title: "Code book"
author: "Paul A. Rubin"
date: "01/16/2015"
output: html_document
---

This code book describes the variables in the data frames produced by the `run_analysis.R` script. The reader is referred to the local "getData.Rmd" document for an explanation of when and how the data was downloaded, and to the [Human Activity Recognition Using Smartphones Data Set](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) web page for more details about the source data.

The `run_analysis.R` script generates two datasets, both documented here. The first (a dataframe named `extractedData`) is a subset of the UCI data; the second (a dataframe named ???, exported to a text file of the same name) contains summary statistics for the first.

## Notes about the extracted data
* Only features representing means or standard deviations were extracted.
* Among those features representing means, only the ones paired with a corresponding standard deviation were extracted. Thus `fBodyGyro-mean()-X` and `fBodyGyro-std()-X` were extracted, but neither `fBodyAccJerk-meanFreq()-X` nor `angle(tBodyGyroMean,gravityMean)` were extracted (there being no corresponding standard deviation feature for either).
* A total of 33 features of each type (means, standard deviations) were extracted.
* Subjects were split between training and testing samples. Those two samples are merged in the extracted data, with no indication of which sample contained each subject. (The subject-sample pairing does not belong in the same table as the extracted data. A separate table for it would be trivial to construct.)
* `NA` values are used for factors not relevant to a particular observation. For instance, `tBodyGyroMag-std()` has no X-Y-Z axis, so the `Direction` value for an observation of that feature will be `NA`.
* Some of the source features contain "BodyBody" in their names, such as `fBodyBodyAccJerkMag-mean()`. There is no explanation on the source web page, and the "features_info.txt" file supplied with the data _seems to suggest_ that these are typographical errors. Nonetheless, they are preserved in the extracted data, so that three acceleration components ("Body", "Gravity" and "BodyBody") are present. The rationale for leaving "BodyBody" alone is to avoid data loss if there is in fact some difference between "Body" and "BodyBody".

# Extracted Data

The extracted data set contains nine factor variables and one numeric variable (**Value**). According to the "README.txt" file accompanying the source data, Value entries have been normalized to the range [-1, 1].

Variable | Description
---------|------------
Subject | the identifying number (1-30) for the subject that produced the observation
Activity | the activity (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING)
Component | the component (Body, BodyBody or Gravity) for accelerator signals 
Device | which device (accelerometer or gyroscope) produced the data
Domain | which domain (time, frequency) applies to the observation
Direction | which axis (X, Y or Z) applies to the observation
Jerk | is this a Jerk signal? (TRUE or FALSE)
Mag | is this the magnitude of a three-dimensional signal vector? (TRUE or FALSE)
Statistic | is this a mean or a standard deviation?
Value | the value of the statistic (mean, standard deviation) captured in this observation
